### ISSUE TITLE
Weird layout details

### ISSUE THREAD

**Issue by u451f** [u451f/criticalinfrastructurelab#10]
There are elements which were either not designed but are being used in markdown and then result in a strange print layout. I'm colleting them below and we should look into why these things happen, if something in the mdwn needs to change or if we want to account for every possible corner case when building the PDF.

CIL006:
- second level titles are italized (I guess that's because they are not actual second level titles)
- executive summary entirely italized and indented as if it were a quote
- page 5 indented text has no paragraphs
- page 42, there's a lot of space in the footnote n° 11
- references lack title "References" as we have in previous publications

**Comment by u451f** [comment]
- CIL005, page 11, page 13 ends on a pulled quote
- CIL005 page 16 ends on a circle
- CIL005 page 18 second level title followed by pulled quote then lacks a non indented 1st paragraph

**Comment by u451f** [comment]
I guess that's for @maxigas to look into

**Comment by maxigas** [comment]
Regarding the pulled quotes that slide down below the main text it would indeed be nice if they can always stay above the footnotes.

Regarding the circle, you can safely forget about it. At some point i produce an updated version where each chapter ends in a circle. I think it is just a nice typographic way to signal that a main chapter ends there, rather than a section.

**Comment by u451f** [comment]
> Page 11 and 13 is _not_ intentional: these two are pulled quotes near the end of the article that ended up below the main text.

Yes, that's hopefully fixed in my last commits - for now with a bit of a dirty hack, but let's see how it turns out. I want to look into it again in detail at a later point in time.

> Page 16 is intentional: i had the idea to end the main chapters with a special character but it seems i failed to follow through to insert a circle at the end of each chapter.

Ack

**Comment by u451f** [comment]
> Regarding the pulled quotes that slide down below the main text it would indeed be nice if they can always stay above the footnotes.

We cannot influence (much) where the footnotes are being inserted. But it makes sense to research this better.

**Comment by u451f** [comment]
Let me get back on this.
In CIL006:
* h1 are used in the text, followed by h2. that was not intially thought to be like that. the h1 in the document is the document title, the chapter titles are h2 and then you can have subtitles which correspond to h3 in markdown. h3 however do not show up in the toc - which can be remedied though and then it would keep the original layout. that said, I'm not opposed to doing it the way you did (i consider that to be "appropriating one's tools"!) only, the h1 pages are then basically empty. your call.
* executive summary entirely italized and indented as if it were a quote → that's something I find weird and I would change
* references lack title "References" as we have in previous publications → looks like you added that now

**Comment by u451f** [comment]
> > Regarding the pulled quotes that slide down below the main text it would indeed be nice if they can always stay above the footnotes.
> 
> We cannot influence (much) where the footnotes are being inserted. But it makes sense to research this better.

I propose to open a separate ticket for looking into that issue. Right now it does not seem urgent to me, do you agree?

**Comment by maxigas** [comment]
> * h1 are used in the text, followed by h2. that was not intially thought to be like that. the h1 in the document is the document title, the chapter titles are h2 and then you can have subtitles which correspond to h3 in markdown. h3 however do not show up in the toc - which can be remedied though and then it would keep the original layout. that said, I'm not opposed to doing it the way you did (i consider that to be "appropriating one's tools"!) only, the h1 pages are then basically empty. your call.

Yes, you can write this down to "user innovation". Indeed, I wanted subchapter titles to show up in the Table of Contents along with chapter titles, and so h1 did well for main chapter titles and h2 for subchapter titles, while h3 section titles remained hidden. I think the title-only pages that open the main chapters are a nice touch. So just let this be. :)

> * executive summary entirely italized and indented as if it were a quote → that's something I find weird and I would change

I agree that it would be good to find another way to emphasise whole sections. Interestingly, in the markdown source these paragraphs are marked up with block quotation (`>`) rather than italics (`*`). Yet, block quotations serve a good purpose as block quotations, so maybe they are not a good choice for this either. (I always missed a "boxed text" syntax and semantics in the mardown specs.) Let me know if you have more ideas about this, and in that case feel free to break it out into a separate issue/ticket.

> * references lack title "References" as we have in previous publications → looks like you added that now

Yes, indeed!
