### ISSUE TITLE
Have the option to generate empty pages

### ISSUE THREAD

**Issue by u451f** [u451f/criticalinfrastructurelab#17]

**Comment by maxigas** [comment]
This is important because of for printing the document need to be so that the total number of pages can be divided by 4. Sometimes empty pages have to be inserted to make this happen. I am using very ugly markup for this now, that is also not very precise/stable.

Here is an example:

```

\ 

\ 

\ 

\ 

\ 

\ 

```

This is because normally I would use `\newpage` as a Latex literal that `pandoc` can consumer, but this time we are *not*  going through Latex when generating PDF output.

**Comment by maxigas** [comment]
I actually see commits and CSS for blank page, trying that out now.

**Comment by maxigas** [comment]
[CIL006.pdf](https://github.com/u451f/criticalinfrastructurelab/files/14304435/CIL006.pdf)

The empty page insertion is working fine with inline HTML like `` this!

However, the footnote goes after the empty page in the attached example -- whic h is something to consider for issue #19 -- so closing this issue now!

**Comment by maxigas** [comment]
For the record the syntax we use for this is the following:

```
<div class="blankpage"></div>
```

(There's also a fancy way of writing the equivalent in pandoc-flavoured markdown.)

**Comment by maxigas** [comment]
For the record, this is what I've been using before we got this defined under `assets` in the style sheet files:

```
<div style="page-break-inside:avoid;page-break-after:always">&nbsp;</div>

```
